name: Publish

on:
  workflow_dispatch:
  push:
    branches: 
    - main
env:
  AZURE_WEBAPP_NAME: Turnus20260730021231
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.0.x'

    - name: Restore
      run: dotnet restore ./Turnus/Turnus.csproj

    - name: Build
      run: dotnet build ./Turnus/Turnus.csproj --configuration Release --no-restore

    - name: Publish
      run: dotnet publish ./Turnus/Turnus.csproj --configuration Release --no-build --output '${{env.AZURE_WEBAPP_PACKAGE_PATH}}'

    - name: Deployment
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{env.AZURE_WEBAPP_NAME}}
        publish-profile: ${{secrets.AZURE_PUBLISH_PROFILE}}
        package: ${{env.AZURE_WEBAPP_PACKAGE_PATH}}
    
    
